# Generated by Django 5.1.1 on 2024-10-05 05:33

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('canava', '0013_alter_softtech_student_id_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='softtech_student_id',
            name='biography',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='softtech_student_id',
            name='course_name',
            field=models.CharField(choices=[('Grapics Design', 'Grapics Design'), ('Office Management', 'Office Management'), ('Web Development (Django)', 'Web Development (Django)'), ('Web Development (Python,Django)', 'Web Development (Python,Django)'), ('Digital Marketing', 'Digital Marketing'), ('Python Programming', 'Python Programming')], max_length=150),
        ),
        migrations.AlterField(
            model_name='softtech_student_id',
            name='interest',
            field=models.CharField(choices=[('Design', 'Design'), ('Development', 'Development'), ('Marketing', 'Marketing')], max_length=150),
        ),
    ]
