# Generated by Django 5.1.1 on 2024-10-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canava', '0015_alter_softtech_student_id_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softtech_student_id',
            name='course_name',
            field=models.CharField(choices=[('Digital Marketing', 'Digital Marketing'), ('Web Development (Python,Django)', 'Web Development (Python,Django)'), ('Grapics Design', 'Grapics Design'), ('Office Management', 'Office Management'), ('Python Programming', 'Python Programming'), ('Web Development (Django)', 'Web Development (Django)')], max_length=150),
        ),
        migrations.AlterField(
            model_name='softtech_student_id',
            name='interest',
            field=models.CharField(choices=[('Design', 'Design'), ('Development', 'Development'), ('Marketing', 'Marketing')], max_length=150),
        ),
    ]
