# Generated by Django 5.1.1 on 2024-10-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canava', '0017_alter_softtech_student_id_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softtech_student_id',
            name='course_name',
            field=models.CharField(choices=[('Grapics Design', 'Grapics Design'), ('Python Programming', 'Python Programming'), ('Web Development (Python,Django)', 'Web Development (Python,Django)'), ('Digital Marketing', 'Digital Marketing'), ('Office Management', 'Office Management'), ('Web Development (Django)', 'Web Development (Django)')], max_length=150),
        ),
    ]
