# Generated by Django 5.1.1 on 2024-10-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canava', '0022_alter_softtech_student_id_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softtech_student_id',
            name='course_name',
            field=models.CharField(choices=[('Web Development (Django)', 'Web Development (Django)'), ('Office Management', 'Office Management'), ('Web Development (Python,Django)', 'Web Development (Python,Django)'), ('Python Programming', 'Python Programming'), ('Grapics Design', 'Grapics Design'), ('Digital Marketing', 'Digital Marketing')], max_length=150),
        ),
        migrations.AlterField(
            model_name='softtech_student_id',
            name='interest',
            field=models.CharField(choices=[('Design', 'Design'), ('Marketing', 'Marketing'), ('Development', 'Development')], max_length=150),
        ),
    ]
